services:
  # Knowledge Repo
  knowledge-repo:
    image: blacksmithop/knowledge_repo:latest
    pull_policy: always
    container_name: knowledge-repo
    ports:
      - "8001:8001"
    networks:
      - app_network
    restart: always
    expose:
      - "8001"  # Expose port 8001 for internal communication

networks:
  app_network:
    driver: bridge