services:

  # Nginx 
  nginx:
    image: nginx:latest
    pull_policy: always
    container_name: nginx
    ports:
      - "80:80"  # Expose port 80 to the host
    networks:
      - app_network
    restart: always  # Ensures the container restarts automatically
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount your custom Nginx config

  # # Knowledge Repo
  knowledge-repo:
    image: blacksmithop/knowledge_repo:latest
    # pull_policy: always
    container_name: knowledge-repo
    ports:
      - "8001:8001"
    networks:
      - app_network
    restart: always
    expose:
      - "8001"  # Expose port 8001 for internal communication

  # MongoDB
  mongodb:
    image: mongo:latest
    pull_policy: always
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    networks:
      - app_network
    restart: always
    
networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data_container:
